config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create ]
  end

  resources :movies do
  end

  resources :bookmarks, only: [ :destroy ]
  # # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  # validates :title, absence: false
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(strong_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def strong_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show ]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boomkarks_helper.rb
module BoomkarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>So you wanna bookmark some movies eh?</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, as: :text %>
  <%= f.association :movie %>
  <%# <%= f.input :movies, as: :select %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1493804714600-6edb1cd93080?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3540&q=80);">
  <div class="container center">
    <h1>Behold our <strong>staff picks</strong> of <strong>Hollywood shlock</strong>!</h1>
    <p>Handpicked garbage straight out of the American propaganda machine! Get it while it's hot!</p>
  </div>
</div>



<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80)">
  Garbage
  <ul>
    <% @lists.each do |list| %>
      <li><%= link_to list.name, list_path(list) %></li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<h1>New garbage!</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to our attrocious lists", lists_path %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<%= link_to "Create Bookmark!", new_list_bookmark_path(@list), class: "btn btn-flat" %>
<ul>
  <% @list.bookmarks.each do |b|%>
  <li>
   <%= b.comment %>
  <%= link_to "Delete",
        bookmark_path(b),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </li>
  <% end  %>
</ul>
<%= link_to "Back to our terrible lists", lists_path %>